### ISSUE TITLE
No corresponding file when to test

### ISSUE THREAD

**Issue by shiwei6523** [xcyan/eccv18_mtvae#1]
Hi,
I met some problems when to execute your code. After downloading preprocessed dataset and pre-trained models, when I tried to generate multiple diverse human motion, I met IO error and there is no corresponding file in the preprocessed dataset.Do I need to download the whole Human3.6M dataset from the official website? Thanks!

**Comment by xcyan** [comment]
Yes. Please download the Human3.6M dataset as our full generation model is
video-conditioned.

Best,
Xinchen

**Comment by xcyan** [comment]
@shiwei6523 Can you confirm if the problem is resolved once you have the dataset downloaded? Thanks!
